-- FIX FOR RX_TX AND DISEASE
-- Execute this to complete partitioning for the 2 failing tables

USE [sqldb-epr-qa];
GO

-- ============ DIAGNOSE RX_TX ============
PRINT 'Diagnosing RX_TX...';
SELECT 
    CONSTRAINT_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'RX_TX' AND TABLE_SCHEMA = 'EPS'
ORDER BY ORDINAL_POSITION;

SELECT 
    COUNT(DISTINCT partition_number) as partition_count
FROM sys.partitions
WHERE object_id=OBJECT_ID('EPS.RX_TX') AND index_id=1;
GO

-- ============ FIX RX_TX ============
-- If RX_TX shows 1 partition, the PK exists but is not on partition scheme
-- Need to drop it and recreate on partition scheme
PRINT 'Fixing RX_TX...';
BEGIN TRY
    -- Drop any child FKs that might still exist
    ALTER TABLE EPS.PACKAGE_INFO DROP CONSTRAINT PACKAGE_INFO_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'PACKAGE_INFO FK already dropped or doesn''t exist';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX_DIAGNOSIS_CODES DROP CONSTRAINT RX_TX_DIAGNOSIS_CODES_FK2;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_DIAGNOSIS_CODES FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX_DUR_LIST DROP CONSTRAINT RX_TX_DUR_LIST_FK_IDRXTX;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_DUR_LIST FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.TX_CRED DROP CONSTRAINT TX_CRED_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'TX_CRED FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.TX_LOT DROP CONSTRAINT TX_LOT_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'TX_LOT FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.TX_TP DROP CONSTRAINT TX_TP_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'TX_TP FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.VIAL_INFO DROP CONSTRAINT VIAL_INFO_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'VIAL_INFO FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.COMPOUND_INGREDIENTS DROP CONSTRAINT COMPOUND_INGREDIENTS_FK2;
END TRY
BEGIN CATCH
    PRINT 'COMPOUND_INGREDIENTS FK already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX_SIG_STRUCTURED_PART DROP CONSTRAINT RX_TX_SIG_STR_PRT_FK_RX_TX;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_SIG_STRUCTURED_PART FK already dropped';
END CATCH

-- Drop outbound FKs
BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ALT_PRESCRIBER;
END TRY
BEGIN CATCH
    PRINT 'RX_TX outbound FKs already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ESCHAIN;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_FK_ESCHAIN already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ESSTORE;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_FK_ESSTORE already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_MOD_PCM;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_FK_MOD_PCM already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_PRESCRIBER;
END TRY
BEGIN CATCH
    PRINT 'RX_TX_FK_PRESCRIBER already dropped';
END CATCH

-- Now drop the existing PK (whether it's PK_RX_TX or RX_TX_PK)
BEGIN TRY
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT PK_RX_TX;
    PRINT 'Dropped PK_RX_TX';
END TRY
BEGIN CATCH
    BEGIN TRY
        ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_PK;
        PRINT 'Dropped RX_TX_PK';
    END TRY
    BEGIN CATCH
        PRINT 'Could not drop PK: ' + ERROR_MESSAGE();
    END CATCH
END CATCH

-- Create partitioned PK
BEGIN TRY
    ALTER TABLE EPS.RX_TX ADD CONSTRAINT PK_RX_TX PRIMARY KEY CLUSTERED (CHAIN_ID, [ID]) ON ps_ChainID_EPS(CHAIN_ID);
    PRINT 'RX_TX: SUCCESS - Partitioned PK created';
END TRY
BEGIN CATCH
    PRINT 'RX_TX: FAILED - ' + ERROR_MESSAGE();
END CATCH
GO

-- ============ CHECK IF DISEASE EXISTS ============
PRINT '';
PRINT 'Checking if DISEASE table exists...';
IF OBJECT_ID('EPS.DISEASE') IS NOT NULL
BEGIN
    PRINT 'DISEASE table exists. Checking current partitions...';
    SELECT COUNT(DISTINCT partition_number) FROM sys.partitions WHERE object_id=OBJECT_ID('EPS.DISEASE') AND index_id=1;
END
ELSE
BEGIN
    PRINT 'ERROR: DISEASE table does not exist!';
END
GO

-- ============ FIX DISEASE ============
PRINT '';
PRINT 'Fixing DISEASE...';
BEGIN TRY
    ALTER TABLE EPS.DISEASE DROP CONSTRAINT DISEASE_FK_ESCHAIN;
END TRY
BEGIN CATCH
    PRINT 'DISEASE_FK_ESCHAIN already dropped or doesn''t exist';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.DISEASE DROP CONSTRAINT DISEASE_FK_ESSTORE;
END TRY
BEGIN CATCH
    PRINT 'DISEASE_FK_ESSTORE already dropped';
END CATCH

BEGIN TRY
    ALTER TABLE EPS.DISEASE DROP CONSTRAINT DISEASE_FK_PATIENT;
END TRY
BEGIN CATCH
    PRINT 'DISEASE_FK_PATIENT already dropped';
END CATCH

-- Drop existing PK
BEGIN TRY
    ALTER TABLE EPS.DISEASE DROP CONSTRAINT PK_DISEASE;
    PRINT 'Dropped PK_DISEASE';
END TRY
BEGIN CATCH
    PRINT 'Could not drop PK_DISEASE: ' + ERROR_MESSAGE();
END CATCH

-- Create partitioned PK
BEGIN TRY
    ALTER TABLE EPS.DISEASE ADD CONSTRAINT PK_DISEASE PRIMARY KEY CLUSTERED (CHAIN_ID, [ID]) ON ps_ChainID_EPS(CHAIN_ID);
    PRINT 'DISEASE: SUCCESS - Partitioned PK created';
END TRY
BEGIN CATCH
    PRINT 'DISEASE: FAILED - ' + ERROR_MESSAGE();
END CATCH
GO

-- ============ FINAL VERIFICATION ============
PRINT '';
PRINT '========== FINAL VERIFICATION ==========';
SELECT 
    'RX_TX' as [Table],
    COUNT(DISTINCT partition_number) as [Partitions],
    CASE WHEN COUNT(DISTINCT partition_number) = 6 THEN 'PASS' ELSE 'FAIL' END as [Status]
FROM sys.partitions
WHERE object_id=OBJECT_ID('EPS.RX_TX') AND index_id=1
UNION ALL
SELECT 
    'DISEASE',
    COUNT(DISTINCT partition_number),
    CASE WHEN COUNT(DISTINCT partition_number) = 6 THEN 'PASS' ELSE 'FAIL' END
FROM sys.partitions
WHERE object_id=OBJECT_ID('EPS.DISEASE') AND index_id=1
ORDER BY [Table];
