-- Single transaction for RX_TX partitioning
USE [sqldb-epr-qa];
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
GO

BEGIN TRANSACTION;

BEGIN TRY
    PRINT 'Step 1: Dropping child table FKs...';
    
    ALTER TABLE EPS.PACKAGE_INFO DROP CONSTRAINT PACKAGE_INFO_FK_RX_TX;
    ALTER TABLE EPS.RX_TX_DIAGNOSIS_CODES DROP CONSTRAINT RX_TX_DIAGNOSIS_CODES_FK2;
    ALTER TABLE EPS.RX_TX_DUR_LIST DROP CONSTRAINT RX_TX_DUR_LIST_FK_IDRXTX;
    ALTER TABLE EPS.TX_CRED DROP CONSTRAINT TX_CRED_FK_RX_TX;
    ALTER TABLE EPS.TX_LOT DROP CONSTRAINT TX_LOT_FK_RX_TX;
    ALTER TABLE EPS.TX_TP DROP CONSTRAINT TX_TP_FK_RX_TX;
    ALTER TABLE EPS.VIAL_INFO DROP CONSTRAINT VIAL_INFO_FK_RX_TX;
    ALTER TABLE EPS.COMPOUND_INGREDIENTS DROP CONSTRAINT COMPOUND_INGREDIENTS_FK2;
    ALTER TABLE EPS.RX_TX_SIG_STRUCTURED_PART DROP CONSTRAINT RX_TX_SIG_STR_PRT_FK_RX_TX;
    
    PRINT 'Child FKs dropped';
    
    PRINT 'Step 2: Dropping outbound FKs from RX_TX...';
    
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ALT_PRESCRIBER;
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ESCHAIN;
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_ESSTORE;
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_MOD_PCM;
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_PRESCRIBER;
    
    PRINT 'Outbound FKs dropped';
    
    PRINT 'Step 3: Dropping existing PK (RX_TX_PK)...';
    
    ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_PK;
    
    PRINT 'PK dropped';
    
    PRINT 'Step 4: Creating new partitioned PK...';
    
    ALTER TABLE EPS.RX_TX ADD CONSTRAINT PK_RX_TX PRIMARY KEY CLUSTERED (CHAIN_ID, [ID]) ON ps_ChainID_EPS(CHAIN_ID);
    
    PRINT 'Partitioned PK created - RX_TX partitioned successfully!';
    
    COMMIT TRANSACTION;
    
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    PRINT 'ERROR: ' + ERROR_MESSAGE();
    PRINT 'ERROR NUMBER: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
    PRINT 'ERROR SEVERITY: ' + CAST(ERROR_SEVERITY() AS VARCHAR(10));
    PRINT 'Transaction rolled back';
END CATCH
GO
