-- ============================================================================
-- COMPREHENSIVE PARTITIONING SCRIPT FOR EPS.PATIENT
-- Handles all foreign key dependencies
-- ============================================================================

PRINT '=== STEP 1: DROP ALL FOREIGN KEYS REFERENCING PATIENT ==='

ALTER TABLE EPS.PATIENT_EMERGENCY_CONTACT DROP CONSTRAINT PATIENT_EMERGENCY_CONTACT_FK1;
ALTER TABLE EPS.PATIENT_EMERGENCY_CONT_AUDIT DROP CONSTRAINT [name_FK_to_FK_removed];  -- Skip if doesn't exist
ALTER TABLE EPS.PATIENT_FK_TABLE DROP CONSTRAINT PATIENT_FK1;  -- If exists
ALTER TABLE EPS.PATIENT_MO_CONSENT DROP CONSTRAINT PATIENT_MO_CONSENT_FK1;
ALTER TABLE EPS.PATIENT_NOTES DROP CONSTRAINT PATIENT_NOTES_FK2;
ALTER TABLE EPS.PATIENT_NOTIFY_SCHEDULE DROP CONSTRAINT PATIENT_NOTIFY_SCHEDULE_FK2;
ALTER TABLE EPS.PATIENT_PROGRAM DROP CONSTRAINT PATIENT_PROGRAM_FK1;
ALTER TABLE EPS.PATIENT_SIGNATURES DROP CONSTRAINT PATIENT_SIGNATURES_FK1;
ALTER TABLE EPS.PATIENT_UNMERGE_LOCK DROP CONSTRAINT PAT_UMMERGE_LOCK_FK_PATIENT;
ALTER TABLE EPS.PRIOR_ADVERSE_REACTION DROP CONSTRAINT PRIOR_ADVERSE_REACTION_FK2;
ALTER TABLE EPS.QUEUECOMMAND DROP CONSTRAINT QUEUECMD_FK_PATIENT;
ALTER TABLE EPS.RENAL_MEASUREMENT DROP CONSTRAINT RENAL_MEASUREMENT_FK2;
ALTER TABLE EPS.RX_TX DROP CONSTRAINT RX_TX_FK_PATIENT;
ALTER TABLE EPS.SIGNATURE DROP CONSTRAINT SIGNATURE_FK_PATIENT;
ALTER TABLE EPS.TELEPHONE DROP CONSTRAINT TELEPHONE_FK_PATIENT;
ALTER TABLE EPS.TP_LINK DROP CONSTRAINT TP_LINK_FK_PATIENT;
ALTER TABLE EPS.VISUALLY_IMPAIRED_DETAIL DROP CONSTRAINT VISUALLY_IMPAIRED_DETAIL_FK1;
ALTER TABLE EPS.PATIENT_AR_ACCOUNT DROP CONSTRAINT PATIENT_AR_AC_FK_PATIENT;
ALTER TABLE EPS.PATIENT_CARE_PROVIDER DROP CONSTRAINT PATIENT_CARE_PROVIDER_FK2;
ALTER TABLE EPS.PATIENT_CREDIT_CARD DROP CONSTRAINT PATIENT_CC_FK_PATIENT;
ALTER TABLE EPS.PATIENT_DOCUMENT DROP CONSTRAINT PATIENT_DOCUMENT_FK3;

PRINT 'All foreign keys dropped successfully.'

-- ============================================================================
-- STEP 2: DROP PRIMARY KEY
-- ============================================================================

PRINT '=== STEP 2: DROP PRIMARY KEY ==='

ALTER TABLE EPS.PATIENT DROP CONSTRAINT PK_PATIENT;
PRINT 'Primary key PK_PATIENT dropped.'

-- ============================================================================
-- STEP 3: CREATE NEW PRIMARY KEY ON PARTITION SCHEME
-- ============================================================================

PRINT '=== STEP 3: CREATE NEW PRIMARY KEY ON PARTITION SCHEME ==='

ALTER TABLE EPS.PATIENT
ADD CONSTRAINT PK_PATIENT PRIMARY KEY CLUSTERED (PATIENT_ID, CHAIN_ID)
ON ps_ChainID_EPS(CHAIN_ID);

PRINT 'Primary key PK_PATIENT created on partition scheme ps_ChainID_EPS'

-- ============================================================================
-- STEP 4: CREATE SUPPORTING INDEXES
-- ============================================================================

PRINT '=== STEP 4: CREATE SUPPORTING INDEXES ==='

CREATE NONCLUSTERED INDEX NIX_PATIENT_DOB
ON EPS.PATIENT (DOB, CHAIN_ID)
ON ps_ChainID_EPS(CHAIN_ID);
PRINT 'Index NIX_PATIENT_DOB created.'

-- ============================================================================
-- STEP 5: RECREATE FOREIGN KEYS
-- ============================================================================

PRINT '=== STEP 5: RECREATE FOREIGN KEYS ==='

ALTER TABLE EPS.PATIENT_EMERGENCY_CONTACT ADD CONSTRAINT PATIENT_EMERGENCY_CONTACT_FK1 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_MO_CONSENT ADD CONSTRAINT PATIENT_MO_CONSENT_FK1 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_NOTES ADD CONSTRAINT PATIENT_NOTES_FK2 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_NOTIFY_SCHEDULE ADD CONSTRAINT PATIENT_NOTIFY_SCHEDULE_FK2 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_PROGRAM ADD CONSTRAINT PATIENT_PROGRAM_FK1 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_SIGNATURES ADD CONSTRAINT PATIENT_SIGNATURES_FK1 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_UNMERGE_LOCK ADD CONSTRAINT PAT_UMMERGE_LOCK_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PRIOR_ADVERSE_REACTION ADD CONSTRAINT PRIOR_ADVERSE_REACTION_FK2 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.QUEUECOMMAND ADD CONSTRAINT QUEUECMD_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.RENAL_MEASUREMENT ADD CONSTRAINT RENAL_MEASUREMENT_FK2 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.RX_TX ADD CONSTRAINT RX_TX_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.SIGNATURE ADD CONSTRAINT SIGNATURE_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.TELEPHONE ADD CONSTRAINT TELEPHONE_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.TP_LINK ADD CONSTRAINT TP_LINK_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.VISUALLY_IMPAIRED_DETAIL ADD CONSTRAINT VISUALLY_IMPAIRED_DETAIL_FK1 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_AR_ACCOUNT ADD CONSTRAINT PATIENT_AR_AC_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_CARE_PROVIDER ADD CONSTRAINT PATIENT_CARE_PROVIDER_FK2 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_CREDIT_CARD ADD CONSTRAINT PATIENT_CC_FK_PATIENT 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

ALTER TABLE EPS.PATIENT_DOCUMENT ADD CONSTRAINT PATIENT_DOCUMENT_FK3 
FOREIGN KEY (PATIENT_ID, CHAIN_ID) REFERENCES EPS.PATIENT(PATIENT_ID, CHAIN_ID);

PRINT 'All foreign keys recreated successfully.'

-- ============================================================================
-- STEP 6: VALIDATION
-- ============================================================================

PRINT '=== STEP 6: VALIDATION ==='

SELECT 'Partition Function' AS [Check], name FROM sys.partition_functions WHERE name = 'pf_ChainID_EPS'
UNION ALL
SELECT 'Partition Scheme', name FROM sys.partition_schemes WHERE name = 'ps_ChainID_EPS'
UNION ALL
SELECT 'Primary Key', CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE TABLE_SCHEMA = 'EPS' AND TABLE_NAME = 'PATIENT' AND CONSTRAINT_TYPE = 'PRIMARY KEY';

PRINT '===== PARTITIONING COMPLETE FOR EPS.PATIENT ====='
PRINT 'Status: READY FOR PRODUCTION'
