-- ============================================================================
-- AUDIT_TIMESTAMP Partition Verification Queries
-- Category B & C Tables (50 + 1 = 51 total)
-- Created: June 28, 2026
-- ============================================================================

-- QUERY 1: Verify partition function boundaries
-- Shows the 8 weekly partition boundaries (RANGE RIGHT)
SELECT '=== PARTITION FUNCTION BOUNDARIES ===' AS Info;
SELECT 
    boundary_id AS PartitionNumber,
    value AS BoundaryValue,
    'Dates >= this value go to partition ' + CAST(boundary_id + 1 AS VARCHAR) AS Description
FROM sys.partition_range_values
WHERE function_id = (SELECT function_id FROM sys.partition_functions WHERE name = 'pf_AUDIT_TIMESTAMP')
ORDER BY boundary_id;

PartitionNumber	BoundaryValue	Description
1	2026-06-15 00:00:00.0	Dates >= this value go to partition 2
2	2026-06-22 00:00:00.0	Dates >= this value go to partition 3
3	2026-06-29 00:00:00.0	Dates >= this value go to partition 4
4	2026-07-06 00:00:00.0	Dates >= this value go to partition 5
5	2026-07-13 00:00:00.0	Dates >= this value go to partition 6
6	2026-07-20 00:00:00.0	Dates >= this value go to partition 7
7	2026-07-27 00:00:00.0	Dates >= this value go to partition 8

-- QUERY 2: Verify partition scheme assignment
-- Shows all tables using ps_AUDIT_TIMESTAMP scheme
SELECT '=== TABLES ON ps_AUDIT_TIMESTAMP SCHEME ===' AS Info;
SELECT 
    OBJECT_NAME(i.object_id) AS TableName,
    i.name AS IndexName,
    i.type_desc AS IndexType,
    ps.name AS PartitionScheme
FROM sys.indexes i
JOIN sys.partition_schemes ps ON i.data_space_id = ps.data_space_id
WHERE ps.name = 'ps_AUDIT_TIMESTAMP'
AND i.index_id IN (0, 1)  -- Heap or clustered index only
ORDER BY OBJECT_NAME(i.object_id);

results:
TableName	IndexName	IndexType	PartitionScheme
ADDRESS_AUDIT	CIX_ADDRESS_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
ALLERGY_AUDIT	CIX_ALLERGY_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
ALT_PRESCRIBER_AUDIT	CIX_ALT_PRESCRIBER_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
AUDIT_ACCESS_LOG	CIX_AUDIT_ACCESS_LOG_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
AUDIT_MESSAGE_CONTENT	CIX_AUDIT_MESSAGE_CONTENT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
CARD_AUDIT	CIX_CARD_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
CHAIN_RX_TX_SHARING_LINK_AUDIT	CIX_CHAIN_RX_TX_SHARING_LINK_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
COMPOUND_INGREDIENTS_AUDIT	CIX_COMPOUND_INGREDIENTS_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
COUNSELING_NOTES_AUDIT	CIX_COUNSELING_NOTES_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
DISEASE_AUDIT	CIX_DISEASE_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
EMAIL_AUDIT	CIX_EMAIL_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
FDB_PAT_ALLERGY_REACTION_AUDIT	CIX_FDB_PAT_ALLERGY_REACTION_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
FDB_PATIENT_ALLERGY_AUDIT	CIX_FDB_PATIENT_ALLERGY_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
FOLLOW_UP_PRESCRIBER_AUDIT	CIX_FOLLOW_UP_PRESCRIBER_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
FREE_FORM_ALLERGY_AUDIT	CIX_FREE_FORM_ALLERGY_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
KP_RXNUM_REF_AUDIT	CIX_KP_RXNUM_REF_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MATCH_KEY_AUDIT	CIX_MATCH_KEY_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MEDICAL_CONDITION_AUDIT	CIX_MEDICAL_CONDITION_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MOD_PCM_AUDIT	CIX_MOD_PCM_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MRN_AUDIT	CIX_MRN_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MTM_PATIENT_ANSWERS_AUDIT	CIX_MTM_PATIENT_ANSWERS_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
MTM_PATIENT_SESSION_AUDIT	CIX_MTM_PATIENT_SESSION_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PA_NUM_AUDIT	CIX_PA_NUM_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PACKAGE_INFO_AUDIT	CIX_PACKAGE_INFO_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_AR_ACCOUNT_AUDIT	CIX_PATIENT_AR_ACCOUNT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_AUDIT	CIX_PATIENT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_CARE_PROVIDER_AUDIT	CIX_PATIENT_CARE_PROVIDER_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_CREDIT_CARD_AUDIT	CIX_PATIENT_CREDIT_CARD_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_EMERGENCY_CONT_AUDIT	CIX_PATIENT_EMERGENCY_CONT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_NOTES_AUDIT	CIX_PATIENT_NOTES_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_NOTIFY_SCHEDULE_AUDIT	CIX_PATIENT_NOTIFY_SCHEDULE_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_PROGRAM_AUDIT	CIX_PATIENT_PROGRAM_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_PROGRAM_CONTACT_AUDIT	CIX_PATIENT_PROGRAM_CONTACT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PATIENT_SIGNATURES_AUDIT	CIX_PATIENT_SIGNATURES_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PAYMENT_AUDIT	CIX_PAYMENT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PRESCRIBER_AUDIT	CIX_PRESCRIBER_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
PRIOR_ADVERSE_REACTION_AUDIT	CIX_PRIOR_ADVERSE_REACTION_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RENAL_MEASUREMENT_AUDIT	CIX_RENAL_MEASUREMENT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RTSSP_AUDIT	CIX_RTSSP_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RX_TX_AUDIT	CIX_RX_TX_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RX_TX_DIAGNOSIS_CODES_AUDIT	CIX_RX_TX_DIAGNOSIS_CODES_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RX_TX_DUR_LIST_AUDIT	CIX_RX_TX_DUR_LIST_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
RX_TX_PAYMENT_AUDIT	CIX_RX_TX_PAYMENT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
SIGNATURE_AUDIT	CIX_SIGNATURE_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
TELEPHONE_AUDIT	CIX_TELEPHONE_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
TP_LINK_AUDIT	CIX_TP_LINK_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
TX_CRED_AUDIT	CIX_TX_CRED_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
TX_LOT_AUDIT	CIX_TX_LOT_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
TX_TP_AUDIT	CIX_TX_TP_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
VIAL_INFO_AUDIT	CIX_VIAL_INFO_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
VISUALLY_IMPAIRED_DETAIL_AUDIT	CIX_VISUALLY_IMPAIRED_DETAIL_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP
WORKMANS_COMP_AUDIT	CIX_WORKMANS_COMP_AUDIT_TS	CLUSTERED	ps_AUDIT_TIMESTAMP

-- QUERY 3: Partition count per table (should be 8 each)
SELECT '=== PARTITION DISTRIBUTION BY TABLE ===' AS Info;
SELECT 
    OBJECT_NAME(object_id) AS TableName,
    COUNT(DISTINCT partition_number) AS PartitionCount,
    SUM(rows) AS TotalRows,
    CASE 
        WHEN COUNT(DISTINCT partition_number) = 8 THEN '✅ CORRECT'
        ELSE '❌ INVALID'
    END AS Status
FROM sys.partitions
WHERE object_id IN (
    OBJECT_ID('EPS.AUDIT_ACCESS_LOG'),
    OBJECT_ID('EPS.AUDIT_MESSAGE_CONTENT'),
    OBJECT_ID('EPS.ADDRESS_AUDIT'),
    OBJECT_ID('EPS.ALLERGY_AUDIT'),
    OBJECT_ID('EPS.ALT_PRESCRIBER_AUDIT'),
    OBJECT_ID('EPS.CARD_AUDIT'),
    OBJECT_ID('EPS.COMPOUND_INGREDIENTS_AUDIT'),
    OBJECT_ID('EPS.COUNSELING_NOTES_AUDIT'),
    OBJECT_ID('EPS.DISEASE_AUDIT'),
    OBJECT_ID('EPS.EMAIL_AUDIT'),
    OBJECT_ID('EPS.FDB_PATIENT_ALLERGY_AUDIT'),
    OBJECT_ID('EPS.FDB_PAT_ALLERGY_REACTION_AUDIT'),
    OBJECT_ID('EPS.FOLLOW_UP_PRESCRIBER_AUDIT'),
    OBJECT_ID('EPS.FREE_FORM_ALLERGY_AUDIT'),
    OBJECT_ID('EPS.KP_RXNUM_REF_AUDIT'),
    OBJECT_ID('EPS.MATCH_KEY_AUDIT'),
    OBJECT_ID('EPS.MEDICAL_CONDITION_AUDIT'),
    OBJECT_ID('EPS.MOD_PCM_AUDIT'),
    OBJECT_ID('EPS.MRN_AUDIT'),
    OBJECT_ID('EPS.MTM_PATIENT_ANSWERS_AUDIT'),
    OBJECT_ID('EPS.MTM_PATIENT_SESSION_AUDIT'),
    OBJECT_ID('EPS.PACKAGE_INFO_AUDIT'),
    OBJECT_ID('EPS.PATIENT_AUDIT'),
    OBJECT_ID('EPS.PATIENT_CARE_PROVIDER_AUDIT'),
    OBJECT_ID('EPS.PATIENT_CREDIT_CARD_AUDIT'),
    OBJECT_ID('EPS.PATIENT_EMERGENCY_CONT_AUDIT'),
    OBJECT_ID('EPS.PATIENT_NOTES_AUDIT'),
    OBJECT_ID('EPS.PATIENT_PROGRAM_AUDIT'),
    OBJECT_ID('EPS.PATIENT_PROGRAM_CONTACT_AUDIT'),
    OBJECT_ID('EPS.PATIENT_SIGNATURES_AUDIT'),
    OBJECT_ID('EPS.PAYMENT_AUDIT'),
    OBJECT_ID('EPS.PA_NUM_AUDIT'),
    OBJECT_ID('EPS.PRESCRIBER_AUDIT'),
    OBJECT_ID('EPS.PRIOR_ADVERSE_REACTION_AUDIT'),
    OBJECT_ID('EPS.RTSSP_AUDIT'),
    OBJECT_ID('EPS.RX_TX_AUDIT'),
    OBJECT_ID('EPS.RX_TX_DIAGNOSIS_CODES_AUDIT'),
    OBJECT_ID('EPS.RX_TX_DUR_LIST_AUDIT'),
    OBJECT_ID('EPS.RX_TX_PAYMENT_AUDIT'),
    OBJECT_ID('EPS.SIGNATURE_AUDIT'),
    OBJECT_ID('EPS.TELEPHONE_AUDIT'),
    OBJECT_ID('EPS.TP_LINK_AUDIT'),
    OBJECT_ID('EPS.TX_CRED_AUDIT'),
    OBJECT_ID('EPS.TX_LOT_AUDIT'),
    OBJECT_ID('EPS.TX_TP_AUDIT'),
    OBJECT_ID('EPS.VIAL_INFO_AUDIT'),
    OBJECT_ID('EPS.WORKMANS_COMP_AUDIT'),
    OBJECT_ID('EPS.PATIENT_AR_ACCOUNT_AUDIT'),
    OBJECT_ID('EPS.RENAL_MEASUREMENT_AUDIT'),
    OBJECT_ID('EPS.PATIENT_NOTIFY_SCHEDULE_AUDIT'),
    OBJECT_ID('EPS.CHAIN_RX_TX_SHARING_LINK_AUDIT'),
    OBJECT_ID('EPS.VISUALLY_IMPAIRED_DETAIL_AUDIT')
)
AND index_id IN (0, 1)
GROUP BY object_id
ORDER BY TableName;

-- QUERY 4: Detailed row distribution by partition for a specific table
-- Usage: Replace 'AUDIT_ACCESS_LOG' with any other table name to check
SELECT '=== DETAILED PARTITION DISTRIBUTION: AUDIT_ACCESS_LOG ===' AS Info;
SELECT 
    p.partition_number AS PartitionNum,
    p.rows AS RowCount,
    CASE 
        WHEN p.partition_number = 1 THEN 'P1: Before 2026-06-15'
        WHEN p.partition_number = 2 THEN 'P2: 2026-06-15 to 2026-06-22'
        WHEN p.partition_number = 3 THEN 'P3: 2026-06-22 to 2026-06-29'
        WHEN p.partition_number = 4 THEN 'P4: 2026-06-29 to 2026-07-06'
        WHEN p.partition_number = 5 THEN 'P5: 2026-07-06 to 2026-07-13'
        WHEN p.partition_number = 6 THEN 'P6: 2026-07-13 to 2026-07-20'
        WHEN p.partition_number = 7 THEN 'P7: 2026-07-20 to 2026-07-27'
        WHEN p.partition_number = 8 THEN 'P8: After 2026-07-27'
    END AS DateRange
FROM sys.partitions p
WHERE object_id = OBJECT_ID('EPS.AUDIT_ACCESS_LOG')
AND index_id = 1
ORDER BY partition_number;

-- QUERY 5: Check if any audit tables have NULL partition (should be 0)
SELECT '=== CHECK FOR UNPARTITIONED ROWS ===' AS Info;
SELECT 
    OBJECT_NAME(object_id) AS TableName,
    SUM(rows) AS UnpartitionedRows,
    CASE WHEN SUM(rows) = 0 THEN '✅ OK' ELSE '⚠️ CHECK' END AS Status
FROM sys.partitions
WHERE object_id IN (
    OBJECT_ID('EPS.AUDIT_ACCESS_LOG'),
    OBJECT_ID('EPS.AUDIT_MESSAGE_CONTENT'),
    OBJECT_ID('EPS.ADDRESS_AUDIT')
)
AND partition_number = 0
GROUP BY object_id
ORDER BY OBJECT_NAME(object_id);

-- QUERY 6: Verify partition elimination capability
-- Shows which partition would be scanned for recent audits
SELECT '=== PARTITION ELIMINATION TEST ===' AS Info;
SELECT 
    'Testing: WHERE AUDIT_TIMESTAMP >= ''2026-07-20''' AS Query,
    'Should access partitions: P7, P8' AS ExpectedPartitions,
    '$PARTITION.pf_AUDIT_TIMESTAMP(CAST(''2026-07-20'' AS datetime2(6)))' AS PartitionCheck;

-- QUERY 7: Sample min/max dates per table (if data exists)
SELECT '=== SAMPLE DATA DISTRIBUTION ===' AS Info;
SELECT 
    OBJECT_NAME(object_id) AS TableName,
    MIN(partition_number) AS FirstPartition,
    MAX(partition_number) AS LastPartition,
    SUM(rows) AS TotalRows
FROM sys.partitions
WHERE object_id IN (
    OBJECT_ID('EPS.AUDIT_ACCESS_LOG'),
    OBJECT_ID('EPS.AUDIT_MESSAGE_CONTENT')
)
AND index_id = 1
GROUP BY object_id
ORDER BY TableName;

-- QUERY 8: Get actual partition numbers for sample date values
SELECT '=== DATE TO PARTITION MAPPING ===' AS Info;
SELECT 
    SampleDate,
    '$PARTITION.pf_AUDIT_TIMESTAMP(CAST(''' + CAST(SampleDate AS VARCHAR) + ''' AS datetime2(6)))' AS PartitionFormula,
    $PARTITION.pf_AUDIT_TIMESTAMP(CAST(SampleDate AS datetime2(6))) AS AssignedPartition
FROM (
    SELECT CAST('2026-06-14' AS datetime2(6)) AS SampleDate
    UNION ALL SELECT CAST('2026-06-15' AS datetime2(6))
    UNION ALL SELECT CAST('2026-06-22' AS datetime2(6))
    UNION ALL SELECT CAST('2026-06-29' AS datetime2(6))
    UNION ALL SELECT CAST('2026-07-06' AS datetime2(6))
    UNION ALL SELECT CAST('2026-07-13' AS datetime2(6))
    UNION ALL SELECT CAST('2026-07-20' AS datetime2(6))
    UNION ALL SELECT CAST('2026-07-27' AS datetime2(6))
    UNION ALL SELECT CAST('2026-08-01' AS datetime2(6))
) dates
ORDER BY SampleDate;

-- QUERY 9: Overall category summary
SELECT '=== CATEGORY B & C SUMMARY ===' AS Info;
SELECT 
    'Total Audit Tables Partitioned' AS Metric,
    COUNT(DISTINCT object_id) AS Value
FROM sys.partitions
WHERE object_id IN (
    SELECT OBJECT_ID(SCHEMA_NAME(schema_id) + '.' + name)
    FROM sys.tables
    WHERE SCHEMA_NAME(schema_id) = 'EPS'
    AND (name LIKE '%AUDIT' OR name = 'VISUALLY_IMPAIRED_DETAIL_AUDIT')
)
AND partition_number > 0;

-- QUERY 10: Verification summary - all 51 tables should have exactly 8 partitions
SELECT '=== FINAL VERIFICATION: 51 TABLES SHOULD ALL SHOW 8 PARTITIONS ===' AS Info;
SELECT 
    SUM(CASE WHEN PartitionCount = 8 THEN 1 ELSE 0 END) AS TablesWithCorrectPartitions,
    COUNT(*) AS TotalAuditTables,
    CASE 
        WHEN SUM(CASE WHEN PartitionCount = 8 THEN 1 ELSE 0 END) = COUNT(*) THEN '✅ ALL CORRECT'
        ELSE '❌ ISSUES FOUND'
    END AS OverallStatus
FROM (
    SELECT 
        OBJECT_NAME(object_id) AS TableName,
        COUNT(DISTINCT partition_number) AS PartitionCount
    FROM sys.partitions
    WHERE object_id IN (
        OBJECT_ID('EPS.AUDIT_ACCESS_LOG'),
        OBJECT_ID('EPS.AUDIT_MESSAGE_CONTENT'),
        OBJECT_ID('EPS.ADDRESS_AUDIT'),
        OBJECT_ID('EPS.ALLERGY_AUDIT'),
        OBJECT_ID('EPS.ALT_PRESCRIBER_AUDIT'),
        OBJECT_ID('EPS.CARD_AUDIT'),
        OBJECT_ID('EPS.COMPOUND_INGREDIENTS_AUDIT'),
        OBJECT_ID('EPS.COUNSELING_NOTES_AUDIT'),
        OBJECT_ID('EPS.DISEASE_AUDIT'),
        OBJECT_ID('EPS.EMAIL_AUDIT'),
        OBJECT_ID('EPS.FDB_PATIENT_ALLERGY_AUDIT'),
        OBJECT_ID('EPS.FDB_PAT_ALLERGY_REACTION_AUDIT'),
        OBJECT_ID('EPS.FOLLOW_UP_PRESCRIBER_AUDIT'),
        OBJECT_ID('EPS.FREE_FORM_ALLERGY_AUDIT'),
        OBJECT_ID('EPS.KP_RXNUM_REF_AUDIT'),
        OBJECT_ID('EPS.MATCH_KEY_AUDIT'),
        OBJECT_ID('EPS.MEDICAL_CONDITION_AUDIT'),
        OBJECT_ID('EPS.MOD_PCM_AUDIT'),
        OBJECT_ID('EPS.MRN_AUDIT'),
        OBJECT_ID('EPS.MTM_PATIENT_ANSWERS_AUDIT'),
        OBJECT_ID('EPS.MTM_PATIENT_SESSION_AUDIT'),
        OBJECT_ID('EPS.PACKAGE_INFO_AUDIT'),
        OBJECT_ID('EPS.PATIENT_AUDIT'),
        OBJECT_ID('EPS.PATIENT_CARE_PROVIDER_AUDIT'),
        OBJECT_ID('EPS.PATIENT_CREDIT_CARD_AUDIT'),
        OBJECT_ID('EPS.PATIENT_EMERGENCY_CONT_AUDIT'),
        OBJECT_ID('EPS.PATIENT_NOTES_AUDIT'),
        OBJECT_ID('EPS.PATIENT_PROGRAM_AUDIT'),
        OBJECT_ID('EPS.PATIENT_PROGRAM_CONTACT_AUDIT'),
        OBJECT_ID('EPS.PATIENT_SIGNATURES_AUDIT'),
        OBJECT_ID('EPS.PAYMENT_AUDIT'),
        OBJECT_ID('EPS.PA_NUM_AUDIT'),
        OBJECT_ID('EPS.PRESCRIBER_AUDIT'),
        OBJECT_ID('EPS.PRIOR_ADVERSE_REACTION_AUDIT'),
        OBJECT_ID('EPS.RTSSP_AUDIT'),
        OBJECT_ID('EPS.RX_TX_AUDIT'),
        OBJECT_ID('EPS.RX_TX_DIAGNOSIS_CODES_AUDIT'),
        OBJECT_ID('EPS.RX_TX_DUR_LIST_AUDIT'),
        OBJECT_ID('EPS.RX_TX_PAYMENT_AUDIT'),
        OBJECT_ID('EPS.SIGNATURE_AUDIT'),
        OBJECT_ID('EPS.TELEPHONE_AUDIT'),
        OBJECT_ID('EPS.TP_LINK_AUDIT'),
        OBJECT_ID('EPS.TX_CRED_AUDIT'),
        OBJECT_ID('EPS.TX_LOT_AUDIT'),
        OBJECT_ID('EPS.TX_TP_AUDIT'),
        OBJECT_ID('EPS.VIAL_INFO_AUDIT'),
        OBJECT_ID('EPS.WORKMANS_COMP_AUDIT'),
        OBJECT_ID('EPS.PATIENT_AR_ACCOUNT_AUDIT'),
        OBJECT_ID('EPS.RENAL_MEASUREMENT_AUDIT'),
        OBJECT_ID('EPS.PATIENT_NOTIFY_SCHEDULE_AUDIT'),
        OBJECT_ID('EPS.CHAIN_RX_TX_SHARING_LINK_AUDIT'),
        OBJECT_ID('EPS.VISUALLY_IMPAIRED_DETAIL_AUDIT')
    )
    AND index_id IN (0, 1)
    GROUP BY object_id
) verification;
